### ISSUE TITLE
Not working with more than 2 peers

### ISSUE THREAD

**Issue by josmangarsal** [P2PSP/Virtual-Room#13] opened 2017-07-20 07:10 UTC
The video keep loading forever. And pause/play messages apear randomly.

![captura de pantalla de 2017-07-20 09-07-52](https://user-images.githubusercontent.com/11162684/28404789-013f1056-6d2b-11e7-86ac-7b91848f7498.png)

**Comment by cristobalmedinalopez** [comment] 2017-07-20 07:53
Hi @josmanual @jainamritanshu,
I guess that the problem is that peers are not sharing its chunks among them. Please, verify that. 
Take into account that we want to follow the DBS set of rules from the P2PSP protocol (_avoid congestion mode_). So, when a peer receives a message from the splitter (sender), the peer saves the chunk and shares it following the peers list, the event of sending is triggered with the reception of a new chunk (from other peers). If the peer receives a chunk from the splitter before it finishes to send its chunk to the entire team, it sends the chunk in a loop (_burst mode_).

Please read about it in the [P2PSP DBS Doc](https://github.com/P2PSP/core/tree/master/doc/DBS). 
Check the P2PSP WebRTC Experiments, specifically the code in channel.onmessage function in [peer.js ](http://www.p2psp.org/webrtc-p2psp-streaming/peer.js)
For further questions ask us on Gitter or Slack.

**Comment by cristobalmedinalopez** [comment] 2017-08-13 20:50
It was fixed in PR #19 where DBS is implemented.

**Closed as completed by cristobalmedinalopez** 2017-08-13 20:50 UTC
Labels: bug
